name: testing
on:
  push:
    branches: [ "wot-py-next" ]
  pull_request:
    branches: [ "wot-py-next" ]

jobs:       
  test-wot-py:
    runs-on: ubuntu-latest
    container:
      image: python:3.7

    services:
      mqtt-broker:
        image: eclipse-mosquitto:1.6
        ports:
          - 1883:1883

    timeout-minutes: 15


    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U .[tests]
    - name: Test with pytest
      run: |
        pytest -sv --disable-warnings --cov=wotpy
      
      env:
        WOTPY_TESTS_MQTT_BROKER_URL: mqtt://localhost:1883
